apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 412144898273.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newName: 412144898273.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newTag: 10dd2ce1
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
